### ISSUE TITLE
Get periodic cell vectors/angles

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#182]
Currently, periodic molecules (equivalent to .ConstructuedMolecule) do not have an easy way of accessing the periodic unit cell. It is used in the construction stage.

Suggesting ConstructedMolecule.get_enclosing_cell():
for periodic molecules, the topology graph._periodic is True: this is the unit cell.
else (i.e. for all other Molecule): This is just some enclosing cube, which does have its uses (can be calculated by projecting atom positions along basis vectors).

An alternative is to have PeriodicConstructedMolecule subclass, which handles this and any future periodic only properties.

I prefer option one; two features for the price of minor ambiguity. But I am unsure of how much overlap is results from it.

**Comment by lukasturcani** [comment]
I suppose the canonical way to do this at the moment would be for `TopologyGraphs`, which do have periodic properties, to provide getter methods which allow access to them. Then a user, who wishes to keep hold of the topology graph, would create a class of the following form in their own code

```python

import stk

class MyConstructedMolecule:
    def __init__(self, topology_graph):
        self.topology_graph = topology_graph
        self.constructed_molecule = stk.ConstructedMolecule(topology_graph)

# The user continues to use MyConstructedMolecule instances,
# making use of the topology graph / constructed molecule as 
# necessary.

```

The obvious disadvantage is that if we want to write periodic structure files with the `write()` method, we can't, because this is all user-code. `stk.ConstructedMolecule` does not keep the topology graph around. Indeed, general utilities for dealing with periodic properties are difficult to add to `stk`, because there is no consistent API for periodic information. Are there any other problems with the current situation I am missing?

The issue I have with adding a method to ConstructedMolecule, is that I do not want the class to get bloated - it should only hold information relevant to all ConstructedMolecule instances. However, gotta say I'm not a huge fan of having multiple ConstructedMolecule classes either, as that makes the `stk` API bloated.

One solution, which might be worth considering, is removing the .write() method. Instead, you would have `Writer` classes, which would be implemented by things like `MdlV3000Writer` or `GulpWriter`. The `GulpWriter` API could be something like 


```python

class GulpWriter:

    def write(self, periodic_info, molecule):
         # Some implementatoin

```


And topology graphs, like `Cof` could have stuff like


```python

class Cof(TopologyGraph):
        def get_periodic_info(self):
             # Returns a standardized API for holding periodic info

```

Then the user API for writing files would be


```python

writer = stk.GulpWriter()
topology_graph = stk.cof.SomeCof()
molecule = stk.ConstructedMolecule(topology_graph)
writer.write(topology_graph.get_periodic_info(), molecule)

```

Arguably clunky ,  but does not bloat any classes with unneccesary API and extendable to other writers.
Note that different writers would NOT be related through an ABC. This would allow them to all have  their
own unique API for their `write()` method.
I also think that having different writers, is a lot more natural than having different types of `ConstructedMolecule`,
some holding periodic info, others not.

Another nice thing could be that this can be added without removing the write() method, at least at first. I don't like
having multiple ways to do 1 thing, but we can give as much time as necessary to switch over to the new API, while keeping
both alive.
