### ISSUE TITLE
Error in alkene functional group code

### ISSUE THREAD

**Issue by zaeemnajeeb** [lukasturcani/stk#236]
In the file defining the Alkene functional group (stk.molecular.functional_groups.alkene.py), lines 103 and 116 return `self.atom1` and `self.atom2`. 
`atom1` and `atom2` do not exist.
Should be `return self._atom1` and `return self._atom2`.

This issue is not picked up with the current tests so suggests a need to see if each atom can be retrieved successfully ( `get_carbon1` etc.) for each functional group.

**Comment by lukasturcani** [comment]
Hi @zaeemnajeeb and thank you for the report! Yep, you are quite right, this needs to be addressed. A bug fix can be done quickly but the missing tests should also be added, probably in a separate PR so that the bug fix can be released ASAP. (The one time I skip unit tests for an interface and there's a bug, go figure).

**Comment by lukasturcani** [comment]
@zaeemnajeeb I fixed the bug in the latest release. Unit tests still need to be added.

**Comment by lukasturcani** [comment]
Since #398 added type hints, these should prevent issues like this in the future.
