### ISSUE TITLE
Improve ConstructedMolecule.__repr__

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#240]
The repr is too bulky and is hard to get any information from. Happy to discuss what might be a better repr! @stevenbennett96 @lukasturcani

**Comment by lukasturcani** [comment]
Yep, very open to suggestions, I agree with this criticism. I guess there are a couple of questions which need to be answered (and of course add more as necessary).

1. How should ``__repr__`` be different from ``__str__``. There are broad Pythonic conventions for this, and I think we should address both methods together.
2. What is a common use-case for each method?
3. What is convenient use-case for each method?
4. Do we want the output of these methods to identify Python instances, or the molecule they represent?
5. Should we implement custom methods, which might fulfill the requirements better, rather than using the Python ones. IE, why are people using these functions? Is there a better way to provide what they need?

**Comment by andrewtarzia** [comment]
I would argue that the main use-case is print(constructued_molecule) as part of debugging OR logging progress:
`Optimising ConstructuedMolecule('A')`

I think the information most useful to be contained is the TopologyGraph name and something about the building blocks? I do not think a smiles string or some string-like representation of the actual molecule contains much human-readable information.

**Comment by stevenbennett96** [comment]
1. I don't think it's significantly important that __repr__ and __str__ are different. I can't see a use case where one would be specifically required over the other.
2 & 3. I agree with Andrew. Whenever you want to log the progress of some function acting on a specific molecule. In such a use case, knowing the molecule object is the same as another molecule object via the console is useful for tracking the progress. 
4. I originally thought seeing the molecule they represent is useful, but it's difficult in the case of cages. Also, how can we ensure this representation is consistent across ConstructedMolecule and BuildingBlock? I think it's better to simply know the objects are the same in terms of their ID or their memory address.
5. I don't particularly think we need them. I can't think of a possible way to include all possible information to construct the molecule from __repr__ without it containing an extremely large amount of information. 

I also want to highlight that the quantity of content within __repr__ is decreasing the speed of lots of optimisation if logging is enabled because so much stuff is being written to stdout.

**Comment by lukasturcani** [comment]
Is there any difference between what information we want during logging, vs what we want during debugging. If so we could use `__repr__` for one and `__str__` for the other.

I agree that generally knowing object ID is more useful. Once molecules get complicated, molecule identifiers quickly become useless for humans.

Good point regarding the speed of logging. I think its very important that it is cheap.

So something like `ConstructedMolecule<FourPlusSix> 0x001233143`
as in `ConstructedMolecule<TopologyGraphName> memoryAddress`
or maybe even
`ConstructedMolecule<FourPlusSix><0x0012931, 0x3321233, 0x3189323> ox003218213` as in
`ConstructedMolecule<TopologyGraphName><buildingBlockMemoryAddress1, buildingBlockMemoryAddress2, ...> memoryAddress`.

Does that sound like what you want? Do you have something else you would rather propose?

**Comment by stevenbennett96** [comment]
I can't think in any case where I would need two different functions now. 
While it is useful that we can build the cages from the output to the console, the cost of speed far outweigh the pros. 
Personally, I prefer the first one with just the memory address of the cage. I think adding building block addresses makes it confusing, i.e. which building block corresponds to which address? Also, which is address is the cage, which is the building block? I think this would be confusing for first time users. 
Also, I don't think we need the topology information. Why not just ``ConstructedMolecule memoryAddress`?

**Comment by lukasturcani** [comment]
To answer your question, the idea would be that the order would be as given by `get_building_blocks()`, which is a canonical order. 

I'll let Andrew address the other points as I don't have a strong preference. I assume the main motivation is that it adds some human-readable information, which can be used to more easily identify the molecule, for a fixed cost, that does not get increase with molecule size. I don't really use this output much, or at all, so I'm not in a position to say how useful that is in practice.

**Comment by lukasturcani** [comment]
I guess, for example, in you get grep logs by topology graph?

**Comment by andrewtarzia** [comment]
I like the shortest option with the memory address above. I would like the topology graph string in there because it is useful to see it when you are building a bunch of different things!

As for the current representation, which can be used to reconstruct the molecule. That could be kept as a different method, as I see it one day having a use...

**Comment by lukasturcani** [comment]
Oh, btw, should we consider changing  the BuildingBlock and Molecule reprs too? Because we might run into similar issues with those. I guess the BuildingBlock one is good, because even if it can get complex with large molecules, for most cases it is what we want. If it is unsuitable in some cases, we can leave it to the user to define and use their own to_string() function, suitable for their logging purposes.


The Molecule one. I guess should be similar to the ConstructedMolecule one?

**Comment by andrewtarzia** [comment]
I would not change the building block one. But the molecule should probably change to match ConstructedMolecule, but I think that is even less likely to be used.

**Comment by stevenbennett96** [comment]
I believe we should change the BuildingBlock and default Molecule reprs to match. Maybe the BuildingBlock one could inherit from the default Molecule repr, as it doesn't contain topology information? ConstructedMolecule could then overwrite the Molecule repr with topology information included?

**Comment by lukasturcani** [comment]
The issue is that molecule I can easily see a Molecule repr being large -> for example if you deposit a ConstructedMolecule into a MoleculeDb and then retrieve it, you will get back a Molecule. So you will be back to writing huge reprs. Again, not sure how likely this is, but I think this should be considered a valid use case and therefore should not have negative performance implications.

**Comment by andrewtarzia** [comment]
Please do not touch the BuildingBlock repr <3

**Comment by lukasturcani** [comment]
So I just realized that `TopologyGraph` is actually an implementation detail of `ConstructedMolecule`. By which I mean, that it is not necessarily true that you need a `TopologyGraph` to make a `ConstructedMolecule`. In the future, it is quite possible that there will be a way to create a `ConstructedMolecule` without any kind of `TopologyGraph`. I therefore will go ahead with 
`<ConstructedMolecule 0x123423>` unless anyone wants to continue the discussion.
