### ISSUE TITLE
how to save periodic structures?

### ISSUE THREAD

**Issue by ltalirz** [lukasturcani/stk#347]
The built-in .mol, .sdf, .pdb and .xyz formats don't include information on the cell vectors.

The [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6585955/) mentions the option to write periodic input files for GULP (added to the codebase [here](https://github.com/lukasturcani/stk/commit/46fb8156e0eacae86b6e02ef808ee8852d73a2c3)) but it seems this function has since been removed again.

What is the suggested way of getting periodic structures out of stk?

**Comment by andrewtarzia** [comment]
Hey! Welcome!

We recently had a new paper on stk come out that is much more up-to-date (PR on updating the docs on this is coming; https://aip.scitation.org/doi/full/10.1063/5.0049708).

stk can write periodic information to Turbomole and pdb format using the `.Writer` classes, which is shown in the example at the bottom and here (https://stk.readthedocs.io/en/stable/stk.molecular.topology_graphs.cof.cof.html).

For GULP usage, we have the software `stko` (https://github.com/JelfsMaterialsGroup/stko), which handles the optimisation and property calculation of molecules from stk. We removed third-party optimisations from stk to simplify the code.

```python
# Accessing the Periodic Information

# When building periodic Cof instances, the periodic information,
# such as the unit cell, can be accessed if you use the 
# PeriodicConstructionResult returned by calling Cof.construct()

import stk

bb1 = stk.BuildingBlock('BrCCBr', [stk.BromoFactory()])
bb2 = stk.BuildingBlock('BrCC(CBr)CBr', [stk.BromoFactory()])

topology_graph = stk.cof.PeriodicHoneycomb(
    building_blocks=(bb1, bb2),
    lattice_size=(3, 3, 1),
)
construction_result = topology_graph.construct()
cof = stk.ConstructedMolecule.init_from_construction_result(
    construction_result=construction_result,
)
periodic_info = construction_result.get_periodic_info()
cell_matrix = periodic_info.get_cell_matrix()
# Can access all unit-cell parameters.
a = periodic_info.get_a()
b = periodic_info.get_b()
c = periodic_info.get_c()
alpha = periodic_info.get_alpha()
beta = periodic_info.get_beta()
gamma = periodic_info.get_gamma()
# Write to .pdb file.
writer = stk.PdbWriter()
writer.write(
    molecule=cof,
    path='cof.pdb',
    periodic_info=periodic_info,
)
```

**Comment by ltalirz** [comment]
Thanks a lot for the quick reply!  I should have seen this in the docs.

It might eventually be useful to think about exposing the `periodic_info` at the `cof` level and handling it in the `cof.write()` function.

**Comment by andrewtarzia** [comment]
No worries, hope you find stk useful!

@lukasturcani can correct me if I am wrong, but we did not do that because of leakage between the ConstructedMolecule and TopologyGraph or something along those lines - i.e. it would require significant changes when the current solution is easy enough to use anyway. 

We would love external feedback, so please chuck any thoughts in the discussions tab as well!

**Comment by lukasturcani** [comment]
For reference, this is the PR with the updated papers https://github.com/lukasturcani/stk/pull/345, I'm gonna merge it at the latest this weekend. 

Yeah the write method *cannot* `write` periodic information. The reason is that the method is on the `ConstructedMolecule` so, it's `ConstructedMolecule.write`. The `ConstructedMolecule` is meant to be a generic class. It therefore does not hold data about periodicity, because such data does not apply to non-periodic moelcules. I could add `ConstructedMolecule` data to all molecules, but I think this complicates the data model. For a couple of reasons

* Every molecule, even non-periodic ones, would require more memory since they have an additional atribute. This is small so I'm not actually very bothered by this. But it does make the class bigger and more complex, which bothers me more. I don't like the idea of making people pay for things they do not use, even if that cost is small. If nothing else, I think it sets a bad precedent that can get out of hand as more things are added.
* The attribute would have to be optional, (either be `None`, or `PeriodicInfo`, or something like that). This means that every time you want to use the periodic info, you have to check if it exists or not -> its an ugly and potentially dangerous API in my opinion, it's very easy to forget to do a check for `None`.
* I could subclass `ConstrcutedMolecule` to something like `PeriodicConstructedMolecule`, and `PeriodicConstructedMolecule` can guarantee that periodic info exists, but I *really* want to have only 1 `ConstructedMolecule` class, because I want the API to be clean, and  I want the code the user should be writing to be obvious. I think having multiple `ConstructedMolecule` classes starts to make this a little bit harder. It also might start a trend of having `ConstructedMolecule` class for everything, `Cage`, `Cof` etc. I think this is redundant because...
* The information already exists on the topology graph. The topology graph can provide more specific information, since it has to hold this information to construct the molecules, so exposing it often comes at no cost.

So my current stance is that, `ConstructedMolecule` -> generic use, everything it contains is valid for all molecules. `TopologyGraph` -> specific information not applicable to all molecules. The rest of the API should then use one of these, depending on if it is providing generic or more specific functionality.

But yeah, not at lot of these comments are of the *I think* form, so if you disagree or if I'm missing something, please let me know.

**Comment by ltalirz** [comment]
I think the subclassing option sounds like the canonical solution to this issue. The subclass of `ConstructedMolecule` (however it's called) would have a pointer to the topology graph, and have a lightweight reimplementation of the `write` function that simply passes on the `periodic_info` to the writer if it exists.

From a user / API perspective I would consider it an improvement, since the way to save periodic and aperiodic structures now becomes the same and the user no longer has to learn two ways of doing it.

**Comment by lukasturcani** [comment]
Ah, a `ConstructedMolecule` cannot have a pointer to the topology graph, because a `TopologyGraph` is not serializable while a `ConstructedMolecule` must be serializable. The reason is that `ConstructedMolecules` have to work with molecular databases out of the box.

The idea is that the user can define their own topology graph, by simply making a new `Vertex` sublcass and implementing
`place_building_block` 
https://stk.readthedocs.io/en/stable/stk.molecular.topology_graphs.topology_graph.vertex.html?highlight=Vertex#stk.molecular.topology_graphs.topology_graph.vertex.Vertex.place_building_block
and `map_functional_groups_to_edges` https://stk.readthedocs.io/en/stable/stk.molecular.topology_graphs.topology_graph.vertex.html?highlight=Vertex#stk.molecular.topology_graphs.topology_graph.vertex.Vertex.map_functional_groups_to_edges


Now you can do this

```python
mol = stk.ConstructedMolecule(MyNewTopologyGraph())
# this just works!
database.put(mol)
```

This works, because `ConstructedMolecule` only holds data for molecules, which is known ahead of time, so serialization can be implemented ahead of time that works any `ConstructedMolecule` instance.   However, the topology graph, holds lots of really specific data required to implement the construction process of that particular class of molecules. If we are to put this data into the database, we need to be able to serialize and deserialize it. However, because this data is really specific, there is no good way of implementing a generic serialization solution. The only option is to make whoever is implementing the `TopologyGraph` to also implement serialization and deserialization methods. Plus depending on which database you want to use, you might need multiple different serialized forms, for example if you want  to use the MongoDB, you would serliaze to JSON, but that would not work with SQL, for example. (What if some custom database is added in the future?) I think this is not a workable restriction to put on topology graph implementors. Therefore, I just don't have any requirements for serializing them. However, this does mean that anything that can be serialized, cannot depend on topology graphs.

A simliar argument is made for BuildingBLock and FunctionalGroup. Building Blocks are actually serialized as plain Molecule instances. That is why `ConstructedMolecule.get_building_block` returns `Molecule` instnaces. But `TopologyGraph.get_building_blocks()` returns `BuildingBLock` insstances.

**Comment by lukasturcani** [comment]
I've considerd removing the `ConstructedMolecule.write` and just using the `Writer` as the 1 and only way to write molecules. But I thought the `ConstructedMolecule.write` was nice convenience for most cases.
